---
title: Dylan Pagillo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Web Developer/Guitarist
username: Dylan Pagillo
user_description: I am a driven and resilient front-end developer and with a unique
  combination of professional experience in web development, marketing, and graphic
  design and a comprehensive academic background focused in both Computer Science
  and Information Design. I’m interested in designing and implementing versatile,
  intuitive user interfaces.
user_title: Web Developer and Designer
email: Dpagillo@gmail.com
twitter_username: DylanPagillo
github_username: DylanNeil
gplus_username: dpagillo@gmail.com
google-analytics:
  id: ''
exclude:
- package.json
- src
- node_modules
